function out = RROEA_NAMES(pt)
global RROEA_COND_START;
RROEA_COND_START = 1;
if (pt == "CHILDREN")
out = [];
elseif (pt == "PARAM_TYPES")
out = ["POOL", "RC", "KE"];
elseif (pt == "MOD")
out = [
    "SC", ...
    "fc16", ...
    "FC", ...
];
elseif (pt == "COND")
out = [
    "GAPDH", ...
    "FBPase", ...
    "SBPase", ...
    "PRK", ...
    "ATPase", ...
    "ATPGPP", ...
    "MDH", ...
    "Thio", ...
    "Fd", ...
    "RuACT", ...
];
elseif (pt == "VEL")
out = [
    "ve2GAPDH", ...
    "ve2FBPase", ...
    "ve2SBPase", ...
    "ve2PRK", ...
    "ve2ATPase", ...
    "ve2ATPGPP", ...
    "ve2MDH", ...
    "ve2Fd", ...
    "veFd2Thio", ...
    "veFd2Calvin", ...
    "ve2RuACT", ...
];
elseif (pt == "POOL")
out = [
"GAPDHT", ...
"FBPaseT", ...
"SBPaseT", ...
"PRKT", ...
"ATPaseT", ...
"ATPGPPT", ...
"MDHT", ...
"ThioT", ...
"FdT", ...
"RuACTT", ...
% Constants used for pool initialization
"SA_GAPDH", ...
"SA_MDH", ...
"SA_PRK", ...
"SA_FBPase", ...
"SA_SBPase", ...
"SA_ATPGPP", ...
"SA_ATPase", ...
"SA_RuACT", ...
"mw_GAPDH", ...
"mw_MDH", ...
"mw_PRK", ...
"mw_FBPase", ...
"mw_SBPase", ...
"mw_ATPGPP", ...
"mw_ATPase", ...
"mw_RuACT", ...
];
elseif (pt == "KE")
out = [
    "KEe2FBPase", ... %	=	RROEA_KE	(	1	)			;
    "KEe2SBPase", ... %	=	RROEA_KE	(	2	)			;
    "KEe2PRK", ... %	=	RROEA_KE	(	3	)			;
    "KEe2ATPase", ... %	=	RROEA_KE	(	4	)			;
    "KEe2RuACT", ... %	=	RROEA_KE	(	5	)			;
    "KEe2GAPDH", ... %	=	RROEA_KE	(	6	)			;
    "KEe2MDH", ... %	=	RROEA_KE	(	7	)			;
    "KEe2ATPGPP", ... %	=	RROEA_KE	(	8	)			;
    "KEeFd2Thio", ... %	=	RROEA_KE	(	9	)			;
];
elseif (pt == "RC")
out = [
    "ke2GAPDH", ... % = RROEA_RC	(	1	)			;	%	The rate constant of electron transfer to GAPDH. From literature. 
    "ke2MDH", ... % = RROEA_RC	(	2	)			;		%	The rate constant of electront transfer to MDH, this rate is totally ASSUMED. 
    "ke2FBPase", ... % = RROEA_RC	(	3	)			;	%	The rate constant of electron transfer from thioredoxin to FBPase.	
    "ke2SBPase", ... % = RROEA_RC	(	4	)			;	%	The rate constant of electron tranfer from thioredoxin to SBPase
    "ke2PRK", ... % = RROEA_RC	(	5	)			;	    %	The rate constant of electron transfer from thioredoxin to PRK, Phosphoribulase kinase
    "ke2RuACT", ... % = RROEA_RC	(	6	)			;	%	The rate constant of electron transfer from thioredoxin to Rubisco activase
    "ke2Fd", ... % = RROEA_RC	(	7	)			;	    %	The rate constant of electron transfer to fe
    "keFd2Thio", ... % = RROEA_RC	(	8	)			;	%	The rate constant of electron transfer from fd to thio
    "keFd2Calvin", ... % = RROEA_RC	(	9	)			;	    %	The rate constant of electron transfer from fd to Calvin cycle
    "ke2ATPGPP", ... % = RROEA_RC	(	10	)			;	    %	The rate constant of electron transfer from fd to ATPGPP
    "Coeff", ...
];
end
end
