function out = XanCycle_NAMES(pt)
global XanCycle_COND_START;
XanCycle_COND_START = 1;
if (pt == "CHILDREN")
out = [];
elseif (pt == "PARAM_TYPES")
out = [];
elseif (pt == "MOD")
out = [
% "activase", ...
"kva", ...
"kaz", ...
"kza", ...
"kav", ...
    "Vx_", ...
    "Ax_", ...
    "Zx_", ...
    "ABA_", ...
    "XanCycle2FIBF_Xstate", ...
];
elseif (pt == "COND")
out = [
"Vx", ...
"Ax", ...
"Zx", ...
"ABA", ...
];
elseif (pt == "VEL")
out = [
    "Vva", ...
    "Vaz", ...
    "Vza", ...
    "Vav", ...
    "Vvf", ...
    "Vv2ABA", ...
    "VABAdg", ...
];
end
end
